In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

data = load_iris()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

models = {
    "Logistic Regression": LogisticRegression(max_iter=200),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC()
}

for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    print(name)
    print("Accuracy:", accuracy_score(y_test, pred))
    print("Confusion matrix:\n", confusion_matrix(y_test, pred))
    print("------")

Logistic Regression
Accuracy: 0.9333333333333333
Confusion matrix:
 [[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
------
Random Forest
Accuracy: 0.9333333333333333
Confusion matrix:
 [[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
------
SVM
Accuracy: 1.0
Confusion matrix:
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
------
